title: Gurban's Blog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Gurban's Blog - blog about everything.

# url
url: "https://dovletov.github.io/"

# excerpts
show_excerpts: true # show excerpts on the home page
excerpt_separator: <!--more-->

# link generation template
permalink: "/:year/:month/:day/:title"

# disqus
disqus:
  shortname: newbies-blog

# ga
# google_analytics: UA-125603404-1
google_analytics: G-8K5F14V55R

# social links
# twitter_username: keydeetter
# github_username:  dovletov
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

paginate: 5
paginate_path: /page:num/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-admin
 - jekyll-octicons
